import React, { useState, useEffect } from 'react';
import { X, Save, Plus } from 'lucide-react';
import { Employee } from '../../types';
import { useAuth } from '../../hooks/useAuth';
import { useDropdownOptions } from '../../hooks/useDropdownOptions';

interface ProjectEmployeeFormProps {
  clientName: string;
  projectName: string;
  onSave: (employee: Omit<Employee, 'id' | 'lastUpdated'>) => void;
  onClose: () => void;
}

export const ProjectEmployeeForm: React.FC<ProjectEmployeeFormProps> = ({ 
  clientName, 
  projectName, 
  onSave, 
  onClose 
}) => {
  const { user } = useAuth();
  const { options, addOption } = useDropdownOptions();
  const [formData, setFormData] = useState({
    employeeId: '',
    name: '',
    email: '',
    department: '',
    designation: '',
    modeOfManagement: 'Managed Service',
    billabilityStatus: 'Billable', // Default to Billable when creating employee for a project
    billing: '',
    // billingCurrency: 'INR' as 'INR' | 'USD' | 'EUR', // DISABLED
    lastActiveDate: '',
    billabilityPercentage: 0,
    projectStartDate: '',
    projectEndDate: '',
    experienceBand: '0-2 years',
    rate: 0,
    // rateCurrency: 'INR' as 'INR' | 'USD' | 'EUR', // DISABLED
    ageing: 0,
    benchDays: 0,
    phoneNumber: '',
    emergencyContact: '',
    ctc: 0,
    // ctcCurrency: 'INR' as 'INR' | 'USD' | 'EUR', // DISABLED
    remarks: '',
    lastModifiedBy: '',

    // Legacy fields
    position: '',
    joiningDate: '',
    location: '',
    manager: '',
    skills: [] as string[],
  });

  const [skillInput, setSkillInput] = useState('');
  const [newOptionInputs, setNewOptionInputs] = useState<{ [key: string]: string }>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Create the employee data object with all required fields
    const employeeData: Omit<Employee, 'id' | 'lastUpdated'> = {
      sNo: 0, // This will be auto-generated by the database
      employeeId: formData.employeeId,
      name: formData.name,
      email: formData.email,
      department: formData.department,
      designation: formData.designation,
      modeOfManagement: formData.modeOfManagement,
      client: clientName, // Fixed client
      billabilityStatus: formData.billabilityStatus,
      // Removed global PO number (PO is per project assignment)
      billing: formData.billing,
      // billingCurrency: formData.billingCurrency, // DISABLED
      lastActiveDate: formData.lastActiveDate,
      projects: projectName, // Fixed project
      billabilityPercentage: formData.billabilityPercentage,
      projectStartDate: formData.projectStartDate,
      projectEndDate: formData.projectEndDate,
      experienceBand: formData.experienceBand,
      rate: formData.rate,
      // rateCurrency: formData.rateCurrency, // DISABLED
      ageing: formData.ageing,
      benchDays: formData.benchDays,
      phoneNumber: formData.phoneNumber,
      emergencyContact: formData.emergencyContact,
      ctc: formData.ctc,
      // ctcCurrency: formData.ctcCurrency, // DISABLED
      remarks: formData.remarks,
      lastModifiedBy: formData.lastModifiedBy,
      position: formData.position,
      joiningDate: formData.joiningDate,
      location: formData.location,
      manager: formData.manager,
      skills: formData.skills,
    };

    onSave(employeeData);
  };

  const addSkill = () => {
    if (skillInput.trim() && !formData.skills.includes(skillInput.trim())) {
      setFormData({
        ...formData,
        skills: [...formData.skills, skillInput.trim()]
      });
      setSkillInput('');
    }
  };

  const handleAddNewOption = async (fieldName: string) => {
    const newValue = newOptionInputs[fieldName]?.trim();
    if (!newValue) return;

    const result = await addOption(fieldName, newValue);
    if (result.success) {
      setFormData({ ...formData, [fieldName === 'mode_of_management' ? 'modeOfManagement' : fieldName === 'billability_status' ? 'billabilityStatus' : fieldName]: newValue });
      setNewOptionInputs({ ...newOptionInputs, [fieldName]: '' });
    } else {
      console.error(`Error adding option: ${result.error}`);
    }
  };

  const removeSkill = (skill: string) => {
    setFormData({
      ...formData,
      skills: formData.skills.filter(s => s !== skill)
    });
  };

  const canEditCTC = user?.role === 'Admin' || user?.role === 'HR';
  const canEditRemarks = user?.role === 'Admin' || user?.role === 'HR';

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-4 sm:p-6 border-b">
          <h2 className="text-lg sm:text-xl font-semibold text-gray-900">
            Add Employee to Project
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Fixed Client and Project Info */}
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 sm:p-6 border-b">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Client (Fixed)
              </label>
              <div className="px-4 py-2 bg-white border border-gray-200 rounded-lg text-gray-900 font-medium">
                {clientName}
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Project (Fixed)
              </label>
              <div className="px-4 py-2 bg-white border border-gray-200 rounded-lg text-gray-900 font-medium">
                {projectName}
              </div>
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-4 sm:p-6 space-y-4 sm:space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Employee ID <span className="text-red-500" title="Required">*</span>
              </label>
              <input
                type="text"
                required
                value={formData.employeeId}
                onChange={(e) => setFormData({ ...formData, employeeId: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Full Name <span className="text-red-500" title="Required">*</span>
              </label>
              <input
                type="text"
                required
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Email <span className="text-red-500" title="Required">*</span>
              </label>
              <input
                type="email"
                required
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Department <span className="text-red-500" title="Required">*</span>
              </label>
              <select
                required
                value={formData.department}
                onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                <option value="EMBEDDED">EMBEDDED</option>
                <option value="IT & FINANCE & ACCOUNTS">IT & FINANCE & ACCOUNTS</option>
                <option value="V&V">V&V</option>
                <option value="SALES & MARKETING">SALES & MARKETING</option>
                <option value="PROJECT MANAGEMENT">PROJECT MANAGEMENT</option>
                <option value="DATA SCIENCE ENGINEERING & TOOLS">DATA SCIENCE ENGINEERING & TOOLS</option>
                <option value="HR & ADMIN">HR & ADMIN</option>
                <option value="OPERATIONS">OPERATIONS</option>
                <option value="FINANCE & ACCOUNTS">FINANCE & ACCOUNTS</option>
                <option value="IT & ADMIN">IT & ADMIN</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Designation <span className="text-red-500" title="Required">*</span>
              </label>
              <input
                type="text"
                required
                value={formData.designation}
                onChange={(e) => setFormData({ ...formData, designation: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Joining Date <span className="text-red-500" title="Required">*</span>
              </label>
              <input
                type="date"
                required
                value={formData.joiningDate}
                onChange={(e) => setFormData({ ...formData, joiningDate: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Location
              </label>
              <select
                value={formData.location}
                onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                <option value="">Select Location</option>
                <option value="Chennai">Chennai</option>
                <option value="Bengaluru">Bengaluru</option>
                <option value="Pune">Pune</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Manager
              </label>
              <input
                type="text"
                value={formData.manager}
                onChange={(e) => setFormData({ ...formData, manager: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
            </div>

            {canEditCTC && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  CTC (Annual)
                </label>
                <div className="flex gap-2">
                  <input
                    type="number"
                    value={formData.ctc}
                    onChange={(e) => setFormData({ ...formData, ctc: parseInt(e.target.value) })}
                    className="flex-1 px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
                  />
                  {/* Currency selection disabled */}
                  {/* <select
                    value={formData.ctcCurrency}
                    onChange={(e) => setFormData({ ...formData, ctcCurrency: e.target.value as 'INR' | 'USD' | 'EUR' })}
                    className="px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
                  >
                    <option value="INR">₹ INR</option>
                    <option value="USD">$ USD</option>
                    <option value="EUR">€ EUR</option>
                  </select> */}
                </div>
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Skills
            </label>
            <div className="flex flex-col sm:flex-row gap-2 mb-2">
              <input
                type="text"
                value={skillInput}
                onChange={(e) => setSkillInput(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addSkill())}
                placeholder="Add a skill..."
                className="flex-1 px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
              <button
                type="button"
                onClick={addSkill}
                className="px-4 py-2 bg-gradient-to-r from-slate-400 to-blue-400 text-white rounded-lg hover:from-slate-500 hover:to-blue-500 transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.skills.map((skill, index) => (
                <span
                  key={index}
                  className="inline-flex items-center px-3 py-1 bg-slate-100 text-slate-700 rounded-full text-sm"
                >
                  {skill}
                  <button
                    type="button"
                    onClick={() => removeSkill(skill)}
                    className="ml-2 text-slate-600 hover:text-slate-800"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          </div>

          {canEditRemarks && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Remarks
              </label>
              <textarea
                value={formData.remarks}
                onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                rows={3}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Mode of Management
            </label>
            <div className="space-y-2">
              <select
                value={formData.modeOfManagement}
                onChange={(e) => setFormData({ ...formData, modeOfManagement: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                {options.mode_of_management?.map((option) => (
                  <option key={option.id} value={option.optionValue}>
                    {option.optionValue}
                  </option>
                ))}
              </select>
              {user?.role === 'Admin' && (
                <div className="flex flex-col sm:flex-row gap-2">
                  <input
                    type="text"
                    placeholder="Add new option..."
                    value={newOptionInputs.mode_of_management || ''}
                    onChange={(e) => setNewOptionInputs({ ...newOptionInputs, mode_of_management: e.target.value })}
                    className="flex-1 px-3 py-1 text-sm border border-slate-200 rounded focus:ring-2 focus:ring-slate-400 focus:border-transparent"
                  />
                  <button
                    type="button"
                    onClick={() => handleAddNewOption('mode_of_management')}
                    className="px-3 py-1 text-sm bg-gradient-to-r from-emerald-300 to-teal-400 text-white rounded hover:from-emerald-400 hover:to-teal-500 transition-colors"
                  >
                    <Plus className="h-3 w-3" />
                  </button>
                </div>
              )}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Billability Status
            </label>
            <div className="space-y-2">
              <select
                value={formData.billabilityStatus}
                onChange={(e) => setFormData({ ...formData, billabilityStatus: e.target.value })}
                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                {options.billability_status?.map((option) => (
                  <option key={option.id} value={option.optionValue}>
                    {option.optionValue}
                  </option>
                ))}
              </select>
              {user?.role === 'Admin' && (
                <div className="flex flex-col sm:flex-row gap-2">
                  <input
                    type="text"
                    placeholder="Add new option..."
                    value={newOptionInputs.billability_status || ''}
                    onChange={(e) => setNewOptionInputs({ ...newOptionInputs, billability_status: e.target.value })}
                    className="flex-1 px-3 py-1 text-sm border border-slate-200 rounded focus:ring-2 focus:ring-slate-400 focus:border-transparent"
                  />
                  <button
                    type="button"
                    onClick={() => handleAddNewOption('billability_status')}
                    className="px-3 py-1 text-sm bg-gradient-to-r from-emerald-300 to-teal-400 text-white rounded hover:from-emerald-400 hover:to-teal-500 transition-colors"
                  >
                    <Plus className="h-3 w-3" />
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Global PO Number removed: PO is per project assignment */}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Billing Rate
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={formData.billing}
                onChange={(e) => setFormData({ ...formData, billing: e.target.value })}
                placeholder="e.g., 100/hour, 5000/month"
                className="flex-1 px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
              {/* Currency selection disabled */}
              {/* <select
                value={formData.billingCurrency}
                onChange={(e) => setFormData({ ...formData, billingCurrency: e.target.value as 'INR' | 'USD' | 'EUR' })}
                className="px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                <option value="INR">₹ INR</option>
                <option value="USD">$ USD</option>
                <option value="EUR">€ EUR</option>
              </select> */}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Billing Last Active Date
            </label>
            <input
              type="date"
              value={formData.lastActiveDate}
              onChange={(e) => setFormData({ ...formData, lastActiveDate: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Billability %
            </label>
            <input
              type="number"
              min="0"
              max="100"
              value={formData.billabilityPercentage}
              onChange={(e) => setFormData({ ...formData, billabilityPercentage: parseFloat(e.target.value) || 0 })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              PO Start Date
            </label>
            <input
              type="date"
              value={formData.projectStartDate}
              onChange={(e) => setFormData({ ...formData, projectStartDate: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              PO End Date
            </label>
            <input
              type="date"
              value={formData.projectEndDate}
              onChange={(e) => setFormData({ ...formData, projectEndDate: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Experience Band
            </label>
            <select
              value={formData.experienceBand}
              onChange={(e) => setFormData({ ...formData, experienceBand: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            >
              {options.experience_band?.map((option) => (
                <option key={option.id} value={option.optionValue}>
                  {option.optionValue}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Rate (Hourly/Daily)
            </label>
            <div className="flex gap-2">
              <input
                type="number"
                min="0"
                step="0.01"
                value={formData.rate}
                onChange={(e) => setFormData({ ...formData, rate: parseFloat(e.target.value) || 0 })}
                className="flex-1 px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              />
              {/* Currency selection disabled */}
              {/* <select
                value={formData.rateCurrency}
                onChange={(e) => setFormData({ ...formData, rateCurrency: e.target.value as 'INR' | 'USD' | 'EUR' })}
                className="px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
              >
                <option value="INR">₹ INR</option>
                <option value="USD">$ USD</option>
                <option value="EUR">€ EUR</option>
              </select> */}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Phone Number
            </label>
            <input
              type="tel"
              value={formData.phoneNumber}
              onChange={(e) => setFormData({ ...formData, phoneNumber: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Emergency Contact
            </label>
            <input
              type="tel"
              value={formData.emergencyContact}
              onChange={(e) => setFormData({ ...formData, emergencyContact: e.target.value })}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-slate-400 focus:border-transparent"
            />
          </div>

          <div className="flex flex-col sm:flex-row justify-end gap-3 sm:gap-4 pt-4 sm:pt-6 border-t">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex items-center justify-center space-x-2 px-6 py-2 bg-gradient-to-r from-slate-400 to-blue-400 text-white rounded-lg hover:from-slate-500 hover:to-blue-500 transition-colors"
            >
              <Save className="h-4 w-4" />
              <span>Add Employee to Project</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};